<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>$(TargetFramework)</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Runtime.Caching" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Libraries\Cache\Maggsoft.Cache.MemoryCache\Maggsoft.Cache.MemoryCache.csproj" />
    <ProjectReference Include="..\..\Libraries\Logging\Maggsoft.Logging\Maggsoft.Logging.csproj" />
    <ProjectReference Include="..\..\Libraries\Maggsoft.Core\Maggsoft.Core.csproj" />
  </ItemGroup>

</Project>
