<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(TargetFramework)</TargetFramework>
		<Copyright>$(Copyright)</Copyright>
		<Company>$(Company)</Company>
		<Authors>$(Authors)</Authors>
		<Version>2.1.0</Version>
		<Description>The Maggsoft.Sqlite.Services</Description>
		<PackageLicenseUrl>$(PackageLicenseUrl)</PackageLicenseUrl>
		<PackageProjectUrl>$(PackageProjectUrl)</PackageProjectUrl>
		<RepositoryUrl>$(RepositoryUrl)</RepositoryUrl>
		<RepositoryType>$(RepositoryType)</RepositoryType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MailKit"/>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Maggsoft.Sqlite\Maggsoft.Sqlite.csproj" />
		<ProjectReference Include="..\Maggsoft.Services\Maggsoft.Services.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Mapper\" />
	</ItemGroup>

</Project>