<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(TargetFramework)</TargetFramework>
		<Copyright>$(Copyright)</Copyright>
		<Company>$(Company)</Company>
		<Authors>$(Authors)</Authors>
		<Version>1.0.1</Version>
		<Description>The Maggsoft.Core project contains a set of core classes for maggsoft, such as caching, events, helpers, and business objects (for example, Order and Customer entities).</Description>
		<PackageLicenseUrl>$(PackageLicenseUrl)</PackageLicenseUrl>
		<PackageProjectUrl>$(PackageProjectUrl)</PackageProjectUrl>
		<RepositoryUrl>$(RepositoryUrl)</RepositoryUrl>
		<PackageIconUrl>$(PackageIconUrl)</PackageIconUrl>
		<RepositoryType>$(RepositoryType)</RepositoryType>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Maggsoft.Mongo\Maggsoft.Mongo.csproj" />
		<ProjectReference Include="..\Maggsoft.Services\Maggsoft.Services.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="AutoMapper" />
		<PackageReference Include="MailKit"  />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions"  />
		<PackageReference Include="MongoDB.Driver" />
	</ItemGroup>
	<ItemGroup>
		<Folder Include="Mapper\" />
	</ItemGroup>
</Project>
