<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>$(TargetFramework)</TargetFramework>
		<Copyright>$(Copyright)</Copyright>
		<Company>$(Company)</Company>
		<Authors>$(Authors)</Authors>
		<Version>1.0.1</Version>
		<Description>The $(MSBuildProjectName).</Description>
		<PackageId>$(MSBuildProjectName)</PackageId>
		<PackageTags>Maggsoft,$(MSBuildProjectName)</PackageTags>
		<PackageLicenseExpression>$(PackageLicenseExpression)</PackageLicenseExpression>
		<PackageProjectUrl>$(PackageProjectUrl)</PackageProjectUrl>
		<RepositoryUrl>$(RepositoryUrl)</RepositoryUrl>
		<RepositoryType>$(RepositoryType)</RepositoryType>
		<PackageIconUrl>$(PackageIconUrl)</PackageIconUrl>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Maggsoft.Mongo\Maggsoft.Mongo.csproj" />
		<ProjectReference Include="..\Maggsoft.Services\Maggsoft.Services.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="$(AutoMapperVersion)" />
		<PackageReference Include="MailKit" Version="$(MailKitVersion)" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="$(MicrosoftExtensionsConfigurationAbstractionsVersion)" />
		<PackageReference Include="MongoDB.Driver" Version="$(MongoDBDriverVersion)" />
	</ItemGroup>
</Project>