<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(TargetFramework)</TargetFramework>
		<Copyright>$(Copyright)</Copyright>
		<Company>$(Company)</Company>
		<Authors>$(Authors)</Authors>
		<Version>1.0.1</Version>
		<PackageId>$(RootNamespace)</PackageId>
		<Description>The $(RootNamespace) project contains a set of core classes for maggsoft, such as caching, events, helpers, and business objects (for example, Order and Customer entities).</Description>
		<PackageLicenseExpression>$(PackageLicenseExpression)</PackageLicenseExpression>
		<PackageLicenseUrl>$(PackageLicenseUrl)</PackageLicenseUrl>
		<PackageProjectUrl>$(PackageProjectUrl)</PackageProjectUrl>
		<RepositoryUrl>$(RepositoryUrl)</RepositoryUrl>
		<RepositoryType>$(RepositoryType)</RepositoryType>
		<PackageIconUrl>$(PackageIconUrl)</PackageIconUrl>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AspectCore.Abstractions" Version="$(AspectCoreAbstractionsVersion)" />
		<PackageReference Include="FluentMigrator" Version="$(FluentMigratorVersion)" />
		<PackageReference Include="FluentMigrator.Runner" Version="$(FluentMigratorRunnerVersion)" />
		<PackageReference Include="FluentMigrator.Runner.SqlServer" Version="$(FluentMigratorRunnerSqlServerVersion)" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="$(MicrosoftEntityFrameworkCoreVersion)" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="$(MicrosoftEntityFrameworkCoreSqlServerVersion)" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="$(MicrosoftEntityFrameworkCoreProxiesVersion)" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="$(MicrosoftEntityFrameworkCoreRelationalVersion)" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="$(MicrosoftExtensionsDependencyInjectionAbstractionsVersion)" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Data\Maggsoft.Data.Mssql\Maggsoft.Data.Mssql.csproj" />
		<ProjectReference Include="..\Data\Maggsoft.Data.Npgsql\Maggsoft.Data.Npgsql.csproj" />
	</ItemGroup>
	
</Project>
