<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(TargetFramework)</TargetFramework>
		<Copyright>$(Copyright)</Copyright>
		<Company>$(Company)</Company>
		<Authors>$(Authors)</Authors>
		<Version>2.1.0</Version>
		<Description>The Maggsoft.Mssql project contains a set of core classes for maggsoft, such as caching, events, helpers, and business objects (for example, Order and Customer entities).</Description>
		<PackageLicenseUrl>$(PackageLicenseUrl)</PackageLicenseUrl>
		<PackageProjectUrl>$(PackageProjectUrl)</PackageProjectUrl>
		<RepositoryUrl>$(RepositoryUrl)</RepositoryUrl>
		<PackageIconUrl>$(PackageIconUrl)</PackageIconUrl>
		<RepositoryType>$(RepositoryType)</RepositoryType>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="AspectCore.Abstractions" />
		<PackageReference Include="FluentMigrator"/>
		<PackageReference Include="FluentMigrator.Runner"/>
		<PackageReference Include="FluentMigrator.Runner.SqlServer"/>

		<PackageReference Include="Microsoft.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational"  />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Data\Maggsoft.Data.Mssql\Maggsoft.Data.Mssql.csproj" />
	</ItemGroup>
</Project>
