<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(TargetFramework)</TargetFramework>
		<Copyright>$(Copyright)</Copyright>
		<Company>$(Company)</Company>
		<Authors>$(Authors)</Authors>
		<Version>2.2.32</Version>
		<Description>The Maggsoft.Framework project contains a set of core classes for maggsoft, such as caching, events, helpers, and business objects (for example, Order and Customer entities).</Description>
		<PackageLicenseUrl>$(PackageLicenseUrl)</PackageLicenseUrl>
		<PackageProjectUrl>$(PackageProjectUrl)</PackageProjectUrl>
		<RepositoryUrl>$(RepositoryUrl)</RepositoryUrl>
		<PackageIconUrl>$(PackageIconUrl)</PackageIconUrl>
		<RepositoryType>$(RepositoryType)</RepositoryType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="DocumentFormat.OpenXml" />
		<PackageReference Include="FastMember" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Core" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" />
		<PackageReference Include="Swashbuckle.AspNetCore" />
		<PackageReference Include="Azure.Extensions.AspNetCore.DataProtection.Keys" />
		<PackageReference Include="Azure.Identity" />
		<PackageReference Include="Azure.Security.KeyVault.Certificates" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Libraries\Data\Maggsoft.Data\Maggsoft.Data.csproj" />
		<ProjectReference Include="..\..\Libraries\Maggsoft.Core\Maggsoft.Core.csproj" />
	</ItemGroup>

</Project>
