<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(TargetFramework)</TargetFramework>
		<Copyright>$(Copyright)</Copyright>
		<Company>$(Company)</Company>
		<Authors>$(Company)</Authors>
		<Version>1.0.7</Version>
		<Description>The $(MSBuildProjectName).</Description>
		<PackageId>$(MSBuildProjectName)</PackageId>
		<PackageTags>Maggsoft,$(MSBuildProjectName)</PackageTags>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>$(PackageProjectUrl)</PackageProjectUrl>
		<RepositoryUrl>$(RepositoryUrl)</RepositoryUrl>
		<RepositoryType>$(RepositoryType)</RepositoryType>
		<PackageIconUrl>https://raw.githubusercontent.com/mehmetunal/maggsoft-logo/main/icon.png</PackageIconUrl>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="DocumentFormat.OpenXml" Version="$(DocumentFormatOpenXmlVersion)" />
		<PackageReference Include="FastMember" Version="$(FastMemberVersion)" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="$(MicrosoftAspNetCoreAuthenticationJwtBearerVersion)" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="$(MicrosoftAspNetCoreMvcCoreVersion)" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="$(MicrosoftAspNetCoreMvcVersioningVersion)" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="$(SwashbuckleAspNetCoreVersion)" />
		<PackageReference Include="Azure.Extensions.AspNetCore.DataProtection.Keys" Version="$(AzureExtensionsAspNetCoreDataProtectionKeysVersion)" />
		<PackageReference Include="Azure.Identity" Version="$(AzureIdentityVersion)" />
		<PackageReference Include="Azure.Security.KeyVault.Certificates" Version="$(AzureSecurityKeyVaultCertificatesVersion)" />
		<PackageReference Include="Microsoft.Extensions.Configuration.AzureKeyVault" Version="$(MicrosoftExtensionsConfigurationAzureKeyVaultVersion)" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\Libraries\Data\Maggsoft.Data\Maggsoft.Data.csproj" />
		<ProjectReference Include="..\..\Libraries\Maggsoft.Core\Maggsoft.Core.csproj" />
	</ItemGroup>
	
</Project>
