<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net5.0</TargetFramework>
		<Copyright>Copyright © Maggsoft, Ltd</Copyright>
		<Company>Maggsoft Bilişim Teknolojileri İthalat İhracat Ticaret, Ltd</Company>
		<Authors>Maggsoft Bilişim Teknolojileri İthalat İhracat Ticaret, Ltd</Authors>
		<Version>0.1.1.0</Version>
		<Description>The Maggsoft.Core project contains a set of core classes for maggsoft, such as caching, events, helpers, and business objects (for example, Order and Customer entities).</Description>
		<PackageLicenseUrl>https://www.maggsoft.com/license</PackageLicenseUrl>
		<PackageProjectUrl>https://www.maggsoft.com/</PackageProjectUrl>
		<RepositoryUrl>https://github.com/mehmetunal/maggsoft</RepositoryUrl>
		<RepositoryType>Git</RepositoryType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="5.0.9" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.0.0" />
		<PackageReference Include="MMLib.RapidPrototyping" Version="1.3.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="5.6.3" />
		<PackageReference Include="Azure.Extensions.AspNetCore.DataProtection.Keys" Version="1.0.2" />
		<PackageReference Include="Azure.Identity" Version="1.3.0" />
		<PackageReference Include="Azure.Security.KeyVault.Certificates" Version="4.1.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.AzureKeyVault" Version="3.1.14" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Libraries\Data\Maggsoft.Data\Maggsoft.Data.csproj" />
		<ProjectReference Include="..\..\Libraries\Maggsoft.Core\Maggsoft.Core.csproj" />
	</ItemGroup>

</Project>
