<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(TargetFramework)</TargetFramework>
		<Copyright>$(Copyright)</Copyright>
		<Company>$(Company)</Company>
		<Authors>$(Authors)</Authors>
		<Version>1.0.4</Version>
		<Description>The Maggsoft.Ocelot.Core.</Description>
		<PackageLicenseUrl>$(PackageLicenseUrl)</PackageLicenseUrl>
		<PackageProjectUrl>$(PackageProjectUrl)</PackageProjectUrl>
		<RepositoryUrl>$(RepositoryUrl)</RepositoryUrl>
		<PackageIconUrl>$(PackageIconUrl)</PackageIconUrl>
		<RepositoryType>$(RepositoryType)</RepositoryType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Ocelot" />
		<PackageReference Include="Ocelot.Cache.CacheManager" />
		<PackageReference Include="MMLib.Ocelot.Provider.AppConfiguration" />
		<PackageReference Include="MMLib.SwaggerForOcelot" />
		<PackageReference Include="Swashbuckle.AspNetCore" />
	</ItemGroup>

</Project>
