<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(TargetFramework)</TargetFramework>
		<Copyright>$(Copyright)</Copyright>
		<Company>$(Company)</Company>
		<Authors>$(Authors)</Authors>
		<Version>1.0.3</Version>
		<Description>The $(MSBuildProjectName).</Description>
		<PackageId>$(MSBuildProjectName)</PackageId>
		<PackageTags>Maggsoft,$(MSBuildProjectName)</PackageTags>
		<PackageLicenseExpression>$(PackageLicenseExpression)</PackageLicenseExpression>
		<PackageProjectUrl>$(PackageProjectUrl)</PackageProjectUrl>
		<RepositoryUrl>$(RepositoryUrl)</RepositoryUrl>
		<RepositoryType>$(RepositoryType)</RepositoryType>
		<PackageIconUrl>$(PackageIconUrl)</PackageIconUrl>
	</PropertyGroup>


	<ItemGroup>
		<PackageReference Include="Ocelot" Version="$(OcelotVersion)" />
		<PackageReference Include="Ocelot.Cache.CacheManager" Version="$(OcelotCacheCacheManagerVersion)" />
		<PackageReference Include="MMLib.Ocelot.Provider.AppConfiguration" Version="$(MMLibOcelotProviderAppConfigurationVersion)" />
		<PackageReference Include="MMLib.SwaggerForOcelot" Version="$(MMLibSwaggerForOcelotVersion)" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="$(SwashbuckleAspNetCoreVersion)" />
	</ItemGroup>

</Project>
