<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(TargetFramework)</TargetFramework>
		<Copyright>$(Copyright)</Copyright>
		<Company>$(Company)</Company>
		<Authors>$(Authors)</Authors>
		<Version>2.0.12</Version>
		<Description>The Maggsoft.Data.Sqlite.</Description>
		<PackageLicenseUrl>$(PackageLicenseUrl)</PackageLicenseUrl>
		<PackageProjectUrl>$(PackageProjectUrl)</PackageProjectUrl>
		<RepositoryUrl>$(RepositoryUrl)</RepositoryUrl>
		<RepositoryType>$(RepositoryType)</RepositoryType>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Maggsoft.Core\Maggsoft.Core.csproj" />
		<ProjectReference Include="..\Maggsoft.Data\Maggsoft.Data.csproj" />
	</ItemGroup>

</Project>
