<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(TargetFramework)</TargetFramework>
		<Nullable>enable</Nullable>
		<Copyright>$(Copyright)</Copyright>
		<Company>$(Company)</Company>
		<Authors>$(Authors)</Authors>
		<Version>2.0.9</Version>
		<Description>The Maggsoft.Endpoints</Description>
		<PackageLicenseUrl>$(PackageLicenseUrl)</PackageLicenseUrl>
		<PackageProjectUrl>$(PackageProjectUrl)</PackageProjectUrl>
		<RepositoryUrl>$(RepositoryUrl)</RepositoryUrl>
		<RepositoryType>$(RepositoryType)</RepositoryType>
	</PropertyGroup>
	
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="Microsoft.Extensions.DependencyModel"  />
	</ItemGroup>
</Project>
