<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(TargetFramework)</TargetFramework>
		<Copyright>$(Copyright)</Copyright>
		<Company>$(Company)</Company>
		<Authors>$(Authors)</Authors>
		<Version>1.0.1</Version>
		<Description>The $(MSBuildProjectName).</Description>
		<PackageId>$(MSBuildProjectName)</PackageId>
		<PackageTags>Maggsoft,$(MSBuildProjectName)</PackageTags>
		<PackageLicenseExpression>$(PackageLicenseExpression)</PackageLicenseExpression>
		<PackageProjectUrl>$(PackageProjectUrl)</PackageProjectUrl>
		<RepositoryUrl>$(RepositoryUrl)</RepositoryUrl>
		<RepositoryType>$(RepositoryType)</RepositoryType>
		<PackageIconUrl>$(PackageIconUrl)</PackageIconUrl>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Autofac" Version="$(AutofacVersion)" />
		<PackageReference Include="Azure.Messaging.ServiceBus" Version="$(AzureMessagingServiceBusVersion)" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="$(MicrosoftExtensionsLoggingAbstractionsVersion)" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Maggsoft.EventBus\Maggsoft.EventBus.csproj" />
	</ItemGroup>

</Project>
