<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Libraries\Data\Maggsoft.Data.Npgsql\Maggsoft.Data.Npgsql.csproj" />
    <ProjectReference Include="..\..\Libraries\Maggsoft.Core\Maggsoft.Core.csproj" />
    <ProjectReference Include="..\..\Libraries\Maggsoft.Npgsql\Maggsoft.Npgsql.csproj" />
    <ProjectReference Include="..\..\Presentation\Maggsoft.Framework\Maggsoft.Framework.csproj" />
  </ItemGroup>

</Project>
