<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>$(TargetFramework)</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Libraries\Data\Maggsoft.Data.Mssql\Maggsoft.Data.Mssql.csproj" />
    <ProjectReference Include="..\..\Libraries\Data\Maggsoft.Data\Maggsoft.Data.csproj" />
    <ProjectReference Include="..\..\Libraries\Dto\Maggsoft.Dto.Mssql\Maggsoft.Dto.Mssql.csproj" />
    <ProjectReference Include="..\..\Libraries\Maggsoft.Core\Maggsoft.Core.csproj" />
    <ProjectReference Include="..\..\Libraries\Maggsoft.Mssql\Maggsoft.Mssql.csproj" />
    <ProjectReference Include="..\..\Libraries\Services\Maggsoft.Services\Maggsoft.Services.csproj" />
    <ProjectReference Include="..\..\Presentation\Maggsoft.Framework\Maggsoft.Framework.csproj" />
  </ItemGroup>

</Project>
