<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Version>1.1.3</Version>
		<Nullable>enable</Nullable>
		<PackAsTool>true</PackAsTool>
		<ToolCommandName>maggsoft</ToolCommandName>
		<PackageLicenseUrl>https://www.maggsoft.com/license</PackageLicenseUrl>
		<!-- CLI aracınızın terminaldeki adı -->
	</PropertyGroup>
</Project>
