<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(TargetFramework)</TargetFramework>
		<Copyright>$(Copyright)</Copyright>
		<Company>$(Company)</Company>
		<Authors>$(Authors)</Authors>
		<Version>2.1.4</Version>
		<Description>The Maggsoft.Core project contains a set of core classes for maggsoft, such as caching, events, helpers, and business objects (for example, Order and Customer entities).</Description>
		<PackageLicenseUrl>$(PackageLicenseUrl)</PackageLicenseUrl>
		<PackageProjectUrl>$(PackageProjectUrl)</PackageProjectUrl>
		<RepositoryUrl>$(RepositoryUrl)</RepositoryUrl>
		<PackageIconUrl>$(PackageIconUrl)</PackageIconUrl>
		<RepositoryType>$(RepositoryType)</RepositoryType>
	</PropertyGroup>
	
	<ItemGroup>
	  <Compile Remove="Events\**" />
	  <Compile Remove="JsonConverters\**" />
	  <EmbeddedResource Remove="Events\**" />
	  <EmbeddedResource Remove="JsonConverters\**" />
	  <None Remove="Events\**" />
	  <None Remove="JsonConverters\**" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="AutoMapper" />
	  <PackageReference Include="Microsoft.Extensions.FileProviders.Abstractions" />
	  <PackageReference Include="Microsoft.Extensions.FileProviders.Physical" />
	  <PackageReference Include="Microsoft.Win32.Registry" />
	  <PackageReference Include="Newtonsoft.Json" />
	  <PackageReference Include="System.Drawing.Common" />
	  <PackageReference Include="System.IO.FileSystem.AccessControl" />
	</ItemGroup>

</Project>
