<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Copyright>Copyright © Maggsoft, Ltd</Copyright>
		<Company>Maggsoft Bilişim Teknolojileri İthalat İhracat Ticaret, Ltd</Company>
		<Authors>Maggsoft Bilişim Teknolojileri İthalat İhracat Ticaret, Ltd</Authors>
		<Version>2.0.4</Version>
		<Description>The Maggsoft.Core project contains a set of core classes for maggsoft, such as caching, events, helpers, and business objects (for example, Order and Customer entities).</Description>
		<PackageId>Maggsoft.Core</PackageId>
		<PackageTags>Maggsoft,Maggsoft.Core,Caching</PackageTags>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://www.maggsoft.com/</PackageProjectUrl>
		<RepositoryUrl>https://github.com/mehmetunal/maggsoft</RepositoryUrl>
		<PackageIconUrl>https://raw.githubusercontent.com/mehmetunal/maggsoft-logo/main/icon.png</PackageIconUrl>
		<RepositoryType>Git</RepositoryType>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Events\**" />
	  <Compile Remove="JsonConverters\**" />
	  <EmbeddedResource Remove="Events\**" />
	  <EmbeddedResource Remove="JsonConverters\**" />
	  <None Remove="Events\**" />
	  <None Remove="JsonConverters\**" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="AutoMapper" Version="12.0.1" />
	  <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
	  <PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="2.2.0" />
	  <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.2" />
	  <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
	  <PackageReference Include="Microsoft.Extensions.FileProviders.Abstractions" Version="8.0.0" />
	  <PackageReference Include="Microsoft.Extensions.FileProviders.Physical" Version="8.0.0" />
	  <PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
	  <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	  <PackageReference Include="System.Drawing.Common" Version="8.0.5" />
	  <PackageReference Include="System.IO.FileSystem.AccessControl" Version="5.0.0" />
	</ItemGroup>

</Project>
