<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(TargetFramework)</TargetFramework>
		<Copyright>$(Copyright)</Copyright>
		<Company>$(Company)</Company>
		<Authors>$(Authors)</Authors>
		<Version>1.0.6</Version>
		<Description>The $(MSBuildProjectName) project contains a set of core classes for maggsoft, such as caching, events, helpers, and business objects (for example, Order and Customer entities).</Description>
		<PackageId>$(MSBuildProjectName)</PackageId>
		<PackageTags>Maggsoft,$(MSBuildProjectName)</PackageTags>
		<PackageLicenseExpression>$(PackageLicenseExpression)</PackageLicenseExpression>
		<PackageProjectUrl>$(PackageProjectUrl)</PackageProjectUrl>
		<RepositoryUrl>$(RepositoryUrl)</RepositoryUrl>
		<RepositoryType>$(RepositoryType)</RepositoryType>
		<PackageIconUrl>$(PackageIconUrl)</PackageIconUrl>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="$(AutoMapperVersion)" />
		<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="$(AutoMapperExtensionsMicrosoftDependencyInjectionVersion)" />
		<PackageReference Include="BCrypt.Net-Next" Version="$(BCryptNetNextVersion)" />
		<PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="$(MicrosoftAspNetCoreHostingAbstractionsVersion)" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="$(MicrosoftAspNetCoreHttpFeaturesVersion)" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="$(MicrosoftAspNetCoreMvcCoreVersion)" />
		<PackageReference Include="Microsoft.Extensions.FileProviders.Abstractions" Version="$(MicrosoftExtensionsFileProvidersAbstractionsVersion)" />
		<PackageReference Include="Microsoft.Extensions.FileProviders.Physical" Version="$(MicrosoftExtensionsFileProvidersPhysicalVersion)" />
		<PackageReference Include="Microsoft.Win32.Registry" Version="$(MicrosoftWin32RegistryVersion)" />
		<PackageReference Include="Newtonsoft.Json" Version="$(NewtonsoftJsonVersion)" />
		<PackageReference Include="System.Drawing.Common" Version="$(SystemDrawingCommonVersion)" />
		<PackageReference Include="System.IO.FileSystem.AccessControl" Version="$(SystemIOFileSystemAccessControlVersion)" />
	</ItemGroup>

</Project>
