<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(TargetFramework)</TargetFramework>
		<Copyright>$(Copyright)</Copyright>
		<Company>$(Company)</Company>
		<Authors>$(Authors)</Authors>
		<Version>1.0.7</Version>
		<Description>The Maggsoft.Core project contains a set of core classes for maggsoft, such as caching, events, helpers, and business objects (for example, Order and Customer entities).</Description>
		<PackageLicenseUrl>$(PackageLicenseUrl)</PackageLicenseUrl>
		<PackageProjectUrl>$(PackageProjectUrl)</PackageProjectUrl>
		<RepositoryUrl>$(RepositoryUrl)</RepositoryUrl>
		<PackageIconUrl>$(PackageIconUrl)</PackageIconUrl>
		<RepositoryType>$(RepositoryType)</RepositoryType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AspectCore.Abstractions"/>
		<PackageReference Include="FluentMigrator" />
		<PackageReference Include="FluentMigrator.Runner"  />
		<PackageReference Include="FluentMigrator.Runner.Postgres" />
		<PackageReference Include="Microsoft.EntityFrameworkCore"/>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Proxies"/>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational"  />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Aspect\Maggsoft.Aspect.Core\Maggsoft.Aspect.Core.csproj" />
		<ProjectReference Include="..\Data\Maggsoft.Data.Npgsql\Maggsoft.Data.Npgsql.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Migrations\" />
	</ItemGroup>

</Project>
