<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(TargetFramework)</TargetFramework>
		<Copyright>$(Copyright)</Copyright>
		<Company>$(Company)</Company>
		<Authors>$(Authors)</Authors>
		<Version>1.0.1</Version>
		<Description>The $(RootNamespace).</Description>
		<PackageId>$(RootNamespace)</PackageId>
		<PackageTags>Maggsoft,$(RootNamespace)</PackageTags>
		<PackageLicenseExpression>$(PackageLicenseExpression)</PackageLicenseExpression>
		<PackageProjectUrl>$(PackageProjectUrl)</PackageProjectUrl>
		<RepositoryUrl>$(RepositoryUrl)</RepositoryUrl>
		<RepositoryType>$(RepositoryType)</RepositoryType>
		<PackageIconUrl>$(PackageIconUrl)</PackageIconUrl>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AspectCore.Abstractions" Version="$(AspectCoreAbstractionsVersion)" />
		<PackageReference Include="FluentMigrator" Version="$(FluentMigratorVersion)" />
		<PackageReference Include="FluentMigrator.Runner" Version="$(FluentMigratorRunnerVersion)" />
		<PackageReference Include="FluentMigrator.Runner.Postgres" Version="$(FluentMigratorRunnerPostgresVersion)" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="$(MicrosoftEntityFrameworkCoreVersion)" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="$(MicrosoftEntityFrameworkCoreProxiesVersion)" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="$(MicrosoftEntityFrameworkCoreRelationalVersion)" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="$(MicrosoftEntityFrameworkCoreRelationalVersion)" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Data\Maggsoft.Data.Npgsql\Maggsoft.Data.Npgsql.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="FluentMigrations\" />
	  <Folder Include="Migrations\" />
	</ItemGroup>
</Project>
