<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net5.0</TargetFramework>
		<Copyright>Copyright © Maggsoft, Ltd</Copyright>
		<Company>Maggsoft Bilişim Teknolojileri İthalat İhracat Ticaret, Ltd</Company>
		<Authors>Maggsoft Bilişim Teknolojileri İthalat İhracat Ticaret, Ltd</Authors>
		<Version>1.0.0</Version>
		<Description>The Maggsoft.Npgsql.</Description>
		<PackageId>Maggsoft.Npgsql</PackageId>
		<PackageTags>Maggsoft,Maggsoft.Npgsql</PackageTags>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://www.maggsoft.com/</PackageProjectUrl>
		<RepositoryUrl>https://github.com/mehmetunal/maggsoft</RepositoryUrl>
		<RepositoryType>Git</RepositoryType>
		<PackageIcon>icon.png</PackageIcon>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AspectCore.Abstractions" Version="2.2.0" />
		<PackageReference Include="FluentMigrator" Version="3.3.2" />
		<PackageReference Include="FluentMigrator.Runner" Version="3.3.2" />
		<PackageReference Include="FluentMigrator.Runner.Postgres" Version="3.3.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="5.0.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="5.0.9" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="5.0.7" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Aspect\Maggsoft.Aspect.Core\Maggsoft.Aspect.Core.csproj" />
		<ProjectReference Include="..\Data\Maggsoft.Data.Npgsql\Maggsoft.Data.Npgsql.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Migrations\" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="..\..\content\icon.png">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>

</Project>
