<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	  <TargetFramework>net5.0</TargetFramework>
	  <Copyright>Copyright © Maggsoft, Ltd</Copyright>
	  <Company>Maggsoft Bilişim Teknolojileri İthalat İhracat Ticaret, Ltd</Company>
	  <Authors>Maggsoft Bilişim Teknolojileri İthalat İhracat Ticaret, Ltd</Authors>
	  <Version>0.1.2</Version>
	  <Description>The Maggsoft.Core project contains a set of core classes for maggsoft, such as caching, events, helpers, and business objects (for example, Order and Customer entities).</Description>
	  <PackageLicenseUrl>https://www.maggsoft.com/license</PackageLicenseUrl>
	  <PackageProjectUrl>https://www.maggsoft.com/</PackageProjectUrl>
	  <RepositoryUrl>https://github.com/mehmetunal/maggsoft</RepositoryUrl>
	  <RepositoryType>Git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Libraries\EventBus\Maggsoft.EventBus.IoC\Maggsoft.EventBus.IoC.csproj" />
  </ItemGroup>

</Project>
