<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
	  <Copyright>Copyright © Maggsoft, Ltd</Copyright>
	  <Company>Maggsoft Bilişim Teknolojileri İthalat İhracat Ticaret, Ltd</Company>
	  <Authors>Maggsoft Bilişim Teknolojileri İthalat İhracat Ticaret, Ltd</Authors>
	  <Version>1.0.1</Version>
	  <Description>The Maggsoft.Data.Mongo entity mongodb(nosql).</Description>
	  <PackageId>Maggsoft.Data.Mongo</PackageId>
	  <PackageTags>Maggsoft,Maggsoft.Data.Mongo</PackageTags>
	  <PackageLicenseExpression>MIT</PackageLicenseExpression>
	  <PackageProjectUrl>https://www.maggsoft.com/</PackageProjectUrl>
	  <RepositoryUrl>https://github.com/mehmetunal/maggsoft</RepositoryUrl>
	  <RepositoryType>Git</RepositoryType>
	  <PackageIconUrl>https://raw.githubusercontent.com/mehmetunal/maggsoft-logo/main/icon.png</PackageIconUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MongoDB.Bson" Version="2.13.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Maggsoft.Data\Maggsoft.Data.csproj" />
  </ItemGroup>

</Project>
