<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(TargetFramework)</TargetFramework>
	  <Copyright>$(Copyright)</Copyright>
	  <Company>$(Company)</Company>
	  <Authors>$(Authors)</Authors>
	  <Version>1.0.1</Version>
	  <Description>The $(MSBuildProjectName) base entity and fluentmigration.</Description>
	  <PackageId>$(MSBuildProjectName)</PackageId>
	  <PackageTags>Maggsoft,$(MSBuildProjectName), FluentMigration</PackageTags>
	  <PackageLicenseExpression>$(PackageLicenseExpressionVersion)</PackageLicenseExpression>
	  <PackageProjectUrl>$(PackageProjectUrl)</PackageProjectUrl>
	  <RepositoryUrl>$(RepositoryUrl)</RepositoryUrl>
	  <RepositoryType>$(RepositoryType)</RepositoryType>
	  <PackageIconUrl>$(PackageIconUrl)</PackageIconUrl>
  </PropertyGroup>


	<ItemGroup>
    <PackageReference Include="FluentMigrator" Version="$(FluentMigratorVersion)" />
    <PackageReference Include="FluentMigrator.Runner" Version="$(FluentMigratorVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Maggsoft.Core\Maggsoft.Core.csproj" />
  </ItemGroup>

</Project>
