<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(TargetFramework)</TargetFramework>
		<Copyright>$(Copyright)</Copyright>
		<Company>$(Company)</Company>
		<Authors>$(Authors)</Authors>
		<Version>2.0.6</Version>
		<Description>The Maggsoft.Core project contains a set of core classes for maggsoft, such as caching, events, helpers, and business objects (for example, Order and Customer entities).</Description>
		<PackageLicenseUrl>$(PackageLicenseUrl)</PackageLicenseUrl>
		<PackageProjectUrl>$(PackageProjectUrl)</PackageProjectUrl>
		<RepositoryUrl>$(RepositoryUrl)</RepositoryUrl>
		<PackageIconUrl>$(PackageIconUrl)</PackageIconUrl>
		<RepositoryType>$(RepositoryType)</RepositoryType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FluentMigrator" />
		<PackageReference Include="FluentMigrator.Runner"/>
		<PackageReference Include="Microsoft.Data.SqlClient" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Maggsoft.Core\Maggsoft.Core.csproj" />
	</ItemGroup>

</Project>
