<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(TargetFramework)</TargetFramework>
		<Copyright>$(Copyright)</Copyright>
		<Company>$(Company)</Company>
		<Authors>$(Authors)</Authors>
		<Version>1.0.1</Version>
		<PackageId>$(MSBuildProjectName)</PackageId>
		<Description>The $(MSBuildProjectName) project contains a set of core classes for maggsoft, such as caching, events, helpers, and business objects (for example, Order and Customer entities).</Description>
		<PackageLicenseExpression>$(PackageLicenseExpression)</PackageLicenseExpression>
		<!--<PackageLicenseUrl>$(PackageLicenseUrl)</PackageLicenseUrl>-->
		<PackageProjectUrl>$(PackageProjectUrl)</PackageProjectUrl>
		<RepositoryUrl>$(RepositoryUrl)</RepositoryUrl>
		<RepositoryType>$(RepositoryType)</RepositoryType>
	</PropertyGroup>

</Project>
