<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Copyright>Copyright © Maggsoft, Ltd</Copyright>
		<Company>Maggsoft Bilişim Teknolojileri İthalat İhracat Ticaret, Ltd</Company>
		<Authors>Maggsoft Bilişim Teknolojileri İthalat İhracat Ticaret, Ltd</Authors>
		<Version>1.0.0.0</Version>
		<Description>The Maggsoft.Core project contains a set of core classes for maggsoft, such as caching, events, helpers, and business objects (for example, Order and Customer entities).</Description>
		<PackageLicenseUrl>https://www.maggsoft.com/license</PackageLicenseUrl>
		<PackageProjectUrl>https://www.maggsoft.com/</PackageProjectUrl>
		<RepositoryUrl>https://github.com/maggsoft/maggsoft</RepositoryUrl>
		<RepositoryType>Git</RepositoryType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.1" />
		<PackageReference Include="Serilog.Enrichers.Environment" Version="2.3.0" />
		<PackageReference Include="Serilog.Settings.Configuration" Version="8.0.0" />
		<PackageReference Include="Serilog.Sinks.Seq" Version="7.0.1" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Aspect\Maggsoft.Aspect.Core\Maggsoft.Aspect.Core.csproj" />
	</ItemGroup>

</Project>
