<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(TargetFramework)</TargetFramework>
	  <Copyright>$(Copyright)</Copyright>
	  <Company>$(Company)</Company>
	  <Authors>$(Authors)</Authors>
	  <Version>1.0.2</Version>
	  <Description>The $(MSBuildProjectName) caching.</Description>
	  <PackageId>$(MSBuildProjectName)</PackageId>
	  <PackageTags>Maggsoft,$(MSBuildProjectName)</PackageTags>
	  <PackageLicenseExpression>$(PackageLicenseExpression)</PackageLicenseExpression>	  
	  <PackageProjectUrl>$(PackageProjectUrl)</PackageProjectUrl>
	  <RepositoryUrl>$(RepositoryUrl)</RepositoryUrl>
	  <RepositoryType>$(RepositoryType)</RepositoryType>
	  <PackageIconUrl>$(PackageIconUrl)</PackageIconUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" Version="$(MessagePackVersion)" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="$(MicrosoftExtensionsDependencyInjectionAbstractionsVersion)" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="$(MicrosoftExtensionsLoggingAbstractionsVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Aspect\Maggsoft.Aspect.Core\Maggsoft.Aspect.Core.csproj" />
  </ItemGroup>

</Project>
