<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(TargetFramework)</TargetFramework>
		<Copyright>$(Copyright)</Copyright>
		<Company>$(Company)</Company>
		<Authors>$(Authors)</Authors>
		<Version>1.0.0.0</Version>
		<Description>The Maggsoft.Core project contains a set of core classes for maggsoft, such as caching, events, helpers, and business objects (for example, Order and Customer entities).</Description>
		<PackageLicenseUrl>$(PackageLicenseUrl)</PackageLicenseUrl>
		<PackageProjectUrl>$(PackageProjectUrl)</PackageProjectUrl>
		<RepositoryUrl>$(RepositoryUrl)</RepositoryUrl>
		<PackageIconUrl>$(PackageIconUrl)</PackageIconUrl>
		<RepositoryType>$(RepositoryType)</RepositoryType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MongoDB.Driver"/>
		<PackageReference Include="MongoDB.Driver.GridFS"/>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Data\Maggsoft.Data.Mongo\Maggsoft.Data.Mongo.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Model" />
	</ItemGroup>

</Project>
