<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <Copyright>Copyright © Maggsoft, Ltd</Copyright>
    <Company>Maggsoft Bilişim Teknolojileri İthalat İhracat Ticaret, Ltd</Company>
    <Authors>Maggsoft Bilişim Teknolojileri İthalat İhracat Ticaret, Ltd</Authors>
    <PackageLicenseUrl>https://www.maggsoft.com/license</PackageLicenseUrl>
    <PackageProjectUrl>https://www.maggsoft.com/</PackageProjectUrl>
    <RepositoryUrl>https://github.com/maggsoft/maggsoft</RepositoryUrl>
    <PackageIconUrl>https://raw.githubusercontent.com/mehmetunal/maggsoft-logo/main/icon.png</PackageIconUrl>
    <RepositoryType>Git</RepositoryType>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="DocumentFormat.OpenXml" Version="3.2.0" />
    <PackageVersion Include="FastMember" Version="1.5.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.5" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Core" Version="2.1.38" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.1.0" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="7.1.0" />
    <PackageVersion Include="Azure.Extensions.AspNetCore.DataProtection.Keys" Version="1.2.3" />
    <PackageVersion Include="Azure.Identity" Version="1.12.0" />
    <PackageVersion Include="Azure.Security.KeyVault.Certificates" Version="4.6.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.AzureKeyVault" Version="3.1.24" />
    <PackageVersion Include="AspectCore.Abstractions" Version="2.4.0" />
    <PackageVersion Include="FluentMigrator" Version="6.2.0" />
    <PackageVersion Include="FluentMigrator.Runner" Version="6.2.0" />
    <PackageVersion Include="FluentMigrator.Runner.SQLite" Version="6.2.0" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Proxies" Version="9.0.0" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.0" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.0" />
    <PackageVersion Include="FluentMigrator.Runner.Postgres" Version="6.2.0" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.1" />
    <PackageVersion Include="FluentMigrator.Runner.SqlServer" Version="6.2.0" />
    <PackageVersion Include="FluentMigrator.Runner.MySql" Version="6.2.0" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />
    <PackageVersion Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
    <PackageVersion Include="MongoDB.Driver" Version="2.25.0" />
    <PackageVersion Include="MongoDB.Driver.GridFS" Version="2.25.0" />
    <PackageVersion Include="AutoMapper" Version="13.0.1" />
    <PackageVersion Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="2.1.1" />
    <PackageVersion Include="Microsoft.AspNetCore.Http" Version="2.1.34" />
    <PackageVersion Include="Microsoft.Extensions.FileProviders.Abstractions" Version="9.0.0" />
    <PackageVersion Include="Microsoft.Extensions.FileProviders.Physical" Version="9.0.0" />
    <PackageVersion Include="Microsoft.Win32.Registry" Version="5.0.0" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageVersion Include="System.Drawing.Common" Version="9.0.0" />
    <PackageVersion Include="System.IO.FileSystem.AccessControl" Version="5.0.0" />
    <PackageVersion Include="MailKit" Version="4.8.0" />
    <PackageVersion Include="RazorEngineCore" Version="2023.11.2" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.0" />
    <PackageVersion Include="Ocelot" Version="23.4.2" />
    <PackageVersion Include="Ocelot.Cache.CacheManager" Version="23.4.2" />
    <PackageVersion Include="MMLib.Ocelot.Provider.AppConfiguration" Version="3.0.0" />
    <PackageVersion Include="MMLib.SwaggerForOcelot" Version="8.3.2" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.0" />
    <PackageVersion Include="Serilog.Enrichers.Environment" Version="3.0.1" />
    <PackageVersion Include="Serilog.Settings.Configuration" Version="8.0.4" />
    <PackageVersion Include="Serilog.Sinks.Seq" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.0" />
    <PackageVersion Include="Polly" Version="8.4.2" />
    <PackageVersion Include="RabbitMQ.Client" Version="6.8.1" />
    <PackageVersion Include="Autofac" Version="8.1.1" />
    <PackageVersion Include="Azure.Messaging.ServiceBus" Version="7.17.5" />
    <PackageVersion Include="Microsoft.Extensions.DependencyModel" Version="9.0.0" />
    <PackageVersion Include="MongoDB.Bson" Version="2.25.0" />
    <PackageVersion Include="Microsoft.Data.SqlClient" Version="5.2.2" />
    <PackageVersion Include="MySqlConnector" Version="2.4.0" />
    <PackageVersion Include="MessagePack" Version="2.5.192" />
    <PackageVersion Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="9.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Caching.Memory" Version="9.0.0" />
    <PackageVersion Include="System.Runtime.Caching" Version="9.0.0" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="8.0.5" />
    <PackageVersion Include="Serilog.AspNetCore" Version="8.0.1" />
    <PackageVersion Include="Serilog.Sinks.MSSqlServer" Version="6.6.0" />
  </ItemGroup>
</Project>