<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Copyright>Copyright © Maggsoft, Ltd</Copyright>
		<Company>Maggsoft Bilişim Teknolojileri İthalat İhracat Ticaret, Ltd</Company>
		<Authors>Maggsoft Bilişim Teknolojileri İthalat İhracat Ticaret, Ltd</Authors>
		<Version>2.0.0</Version>
		<Description>The Maggsoft.Services.</Description>
		<PackageProjectUrl>https://www.maggsoft.com/</PackageProjectUrl>
		<RepositoryUrl>https://github.com/mehmetunal/maggsoft</RepositoryUrl>
		<PackageIconUrl>https://raw.githubusercontent.com/mehmetunal/maggsoft-logo/main/icon.png</PackageIconUrl>
		<RepositoryType>Git</RepositoryType>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.9" />
	  <PackageReference Include="RazorEngineCore" Version="2022.8.1" />
	</ItemGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\..\Data\Maggsoft.Data\Maggsoft.Data.csproj" />
		<ProjectReference Include="..\..\Maggsoft.Core\Maggsoft.Core.csproj" />
	</ItemGroup>

</Project>