<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(TargetFramework)</TargetFramework>
		<Copyright>$(Copyright)</Copyright>
		<Company>$(Company)</Company>
		<Authors>$(Authors)</Authors>
		<Version>2.0.2</Version>
		<Description>The Maggsoft.Services.</Description>
		<PackageLicenseUrl>$(PackageLicenseUrl)</PackageLicenseUrl>
		<PackageProjectUrl>$(PackageProjectUrl)</PackageProjectUrl>
		<RepositoryUrl>$(RepositoryUrl)</RepositoryUrl>
		<PackageIconUrl>$(PackageIconUrl)</PackageIconUrl>
		<RepositoryType>$(RepositoryType)</RepositoryType>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.EntityFrameworkCore" />
	  <PackageReference Include="RazorEngineCore" />
	</ItemGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\..\Data\Maggsoft.Data\Maggsoft.Data.csproj" />
		<ProjectReference Include="..\..\Maggsoft.Core\Maggsoft.Core.csproj" />
	</ItemGroup>

</Project>