<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(TargetFramework)</TargetFramework>
		<Copyright>$(Copyright)</Copyright>
		<Company>$(Company)</Company>
		<Authors>$(Authors)</Authors>
		<Version>1.0.1</Version>
		<Description>The $(RootNamespace).</Description>
		<PackageId>$(RootNamespace)</PackageId>
		<PackageTags>Maggsoft,$(RootNamespace)</PackageTags>
		<PackageLicenseExpression>$(PackageLicenseExpression)</PackageLicenseExpression>
		<PackageProjectUrl>$(PackageProjectUrl)</PackageProjectUrl>
		<RepositoryUrl>$(RepositoryUrl)</RepositoryUrl>
		<RepositoryType>$(RepositoryType)</RepositoryType>
		<PackageIconUrl>$(PackageIconUrl)</PackageIconUrl>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.EntityFrameworkCore" Version="$(MicrosoftEntityFrameworkCoreVersion)" />
	  <PackageReference Include="RazorEngineCore" Version="$(RazorEngineCoreVersion)" />
	</ItemGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\..\Data\Maggsoft.Data\Maggsoft.Data.csproj" />
		<ProjectReference Include="..\..\Maggsoft.Core\Maggsoft.Core.csproj" />
	</ItemGroup>

</Project>