name: Publish Changed Projects

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Determine changed projects
      id: changes
      run: |
        echo "CHANGED_PROJECTS=$(git diff --name-only HEAD^ HEAD | grep -E 'src/.*\.csproj' | cut -d/ -f2 | uniq)" >> $GITHUB_ENV

    - name: Restore dependencies
      run: |
        for project in ${{ env.CHANGED_PROJECTS }}; do
          dotnet restore src/$project/$project.csproj --ignore-failed-sources
        done

    - name: Build
      run: |
        for project in ${{ env.CHANGED_PROJECTS }}; do
          dotnet build src/$project/$project.csproj --configuration Release --no-restore
        done

    - name: Pack
      run: |
        for project in ${{ env.CHANGED_PROJECTS }}; do
          dotnet pack src/$project/$project.csproj --configuration Release --no-build --output ./nupkg /p:Version=$(git rev-parse --short HEAD)
        done

    - name: Publish to GitHub Packages
      run: |
        for package in ./nupkg/*.nupkg; do
          dotnet nuget push $package --api-key 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 --source https://nuget.pkg.github.com/mehmetunal/index.json
          #dotnet nuget push $package --source "maggsoft_github"
        done
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}